version: '3.0'
services:
  frontend:
    image: node:18-alpine
    volumes:
      - ./crawler_frontend:/opt/app
    working_dir: /opt/app
    command: npm install && npm start
    environment:
      - REACT_APP_BACKEND_WS_URL=ws://127.0.0.1:8080
    hostname: frontend
    ports:
      - 3000:3000
  backend:
    hostname: backend
    image: lehoanglong/go_playwright
    volumes:
      - ./crawler_go:/opt/app
    working_dir: /opt/app
    command: go run cmd/main.go
    ports:
      - 8080:8080
  