version: '3.0'
services:
  frontend:
    image: lehoanglong/crawler_frontend
    working_dir: /opt/app
    command: serve -s build
    hostname: frontend
  backend:
    hostname: backend
    image: lehoanglong/crawler_backend
    working_dir: /opt/app
    environment:
      - PORT=80
    command: main
  nginx: 
    image: nginx:1.23.1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/conf
    command: sleep infinity

  